### ISSUE TITLE
Errors upon Install of Blueprint.

### ISSUE THREAD

**Issue by GrantBfoto** [ajam/tarbell-big-read-template#2]
I have used Tarbell (love the Flickety blueprint) a few times now. Am itching to install your blueprint. I am running into this error message when I attempt to install. This Gist shows details. Suggestions? Thanks. https://gist.github.com/GrantBfoto/8de87d4e4f3d36097052

**Comment by joannaskao** [comment]
What version of Tarbell do you have? I know that it doesn't work properly in Tarbell 1.0. You might want to try installing the blueprint in the newest version, 1.0.4 (might be a good idea to use a new virtualenv if you're using one now).

I believe there are also some new library dependencies, so you might want to `pip install requirements.txt` as well.

Let me know if that works!
