### ISSUE TITLE
Can't install tarbell

### ISSUE THREAD

**Issue by cgobbet** [ajam/tarbell-big-read-template#3]
Hello;

I am trying to install tarbell but receive the error message below (pip, python, virtualenv and virtualenvwrapper all successfully installed)

Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/private/var/folders/3z/kd_ybxm91fdgtnm85782x2v00000gn/T/pip-build-cIHu4t/keyring/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/3z/kd_ybxm91fdgtnm85782x2v00000gn/T/pip-WkHFkU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3z/kd_ybxm91fdgtnm85782x2v00000gn/T/pip-build-cIHu4t/keyring

I've followed a handful of tutorials to solve the issue installing BeautifulSoup, Pyglet, ensured I have access to Python Folder (https://github.com/sindresorhus/weechat-notification-center/issues/1)
Can someone help me here?

Thanks a lot and my best wishes

**Comment by eads** [comment]
Hi there. What OS are you using? Tarbell doesn't support Windows, for what it's worth.

You're not the only person struggling with keyring. I'll try and dig around and see what's up. But I suspect you're missing the proper compilation tools.

**Comment by cgobbet** [comment]
Hi, David. Thanks for the prompt response.

I am using OSX El Capitan. I tried several ways to do it, including disabling System Integrity Protection, to no avail (I've already enabled it back).

If you feel that I may be missing something, would u mind me doing a list of them? I can check and install what is missing.

Thanks a lot and my best wishes

**Comment by eads** [comment]
Have you disabled System Integrity Protection _and_ updated homebrew and xcode?

**Comment by cgobbet** [comment]
No, I had just disabled SIP but have not updated anything. Should I give a try?

**Comment by eads** [comment]
Yeah, I think so. I don't have El Capitan yet, so it's hard to diagnose directly. But I think your compiling tools are out of date. I've had similar problems with previous OS X upgrades, though without the added wrinkle of SIP. I suspect you'll want to upgrade Xcode first, then homebrew, since homebrew to some degree depends on tools from Xcode.

**Comment by cgobbet** [comment]
David, solved;

I've installed both Brew and XCode (which were missing). Plus, I believe I was making a mistake when typing the line

export WORKON_HOME=$HOME/.virtualenvs; export PROJECT_HOME=$HOME/Devel; source /usr/local/bin/virtualenvwrapper.sh

Tarbell installed and will work on that from tomorrow.

Your help was invaluable! Thanks a lot!

**Comment by cgobbet** [comment]
David, hello;

I’m afraid I am lost again. I believe I know most of the steps to create a Tarbell project (actually, I created one). The point is that now I simply don’t know how to ‘turn Tarbell on’ (when I try to run any command on Terminal, it says the command is not found).

This is probably a silly question but how do I ‘start’ the program after I reboot? Is there something I am missing and to handle the project I created the place is not Terminal at all?

Sorry for the dummy questions.

Thanks a lot and my best wishes

Cassiano Gobbet  
cassiano.gobbet@gmail.com  

   

On October 4, 2015 at 4:03:39 PM, David Eads (notifications@github.com) wrote:

Yeah, I think so. I don't have El Capitan yet, so it's hard to diagnose directly. But I think your compiling tools are out of date. I've had similar problems with previous OS X upgrades, though without the added wrinkle of SIP. I suspect you'll want to upgrade Xcode first, then homebrew, since homebrew to some degree depends on tools from Xcode.

**Comment by joannaskao** [comment]
Ah good question. To get back into your virtualenv, type in 'workon tarbell1.0.4' or whatever you named your virtualenv (if it wasn't named tarbell1.0.4). 

Did that work?

**Comment by cgobbet** [comment]
Well, not actually (but I am pretty sure I named it tarbell1.0.4 exactly to avoid problems).

is there a way for me to list the name of the virtualenvs I have created? I definitely managed to do it as I went through the whole Tarbell install (until the You got it!). I have even checked if all requisites (Python, virtualenv, pip, virtualenvwrapper, etc) and they were good, so I should be missing something.

One thing I find odd: when I open terminal, the line does not have only the name of my computer, but also the name of a Time Capsule, following the format:

nameofthetimecapsule-2:~nameofcomputer$

(I hadn’t noticed it before…)

So, thanks a lot for the help, David (in advance… :-)

Cassiano Gobbet  
cassiano.gobbet@gmail.com  

   

On October 6, 2015 at 8:50:55 PM, Joanna S. Kao (notifications@github.com) wrote:

Ah good question. To get back into your virtualenv, type in 'workon tarbell1.0.4' or whatever you named your virtualenv (if it wasn't named tarbell1.0.4).

Did that work?

**Comment by joannaskao** [comment]
Typing in `lsvirtualenv` should list your current virtualenvs.

**Comment by cgobbet** [comment]
Any command I type brings me the response: 

-bash: lsvirtualenv: command not found

Should I consider install it again? Or create a different virtualenv?

Cassiano Gobbet  
cassiano.gobbet@gmail.com  

   

On October 6, 2015 at 10:09:19 PM, Joanna S. Kao (notifications@github.com) wrote:

Typing in lsvirtualenv should list your current virtualenvs.

**Comment by eads** [comment]
It seems like you don't have virtualenv installed properly.

It seems quite possible you have it but it needs to be called when your
terminal fires up. Check out the virtualenv bits of
http://blog.apps.npr.org/2013/06/06/how-to-setup-a-developers-environment.html

In the short term, run this in your terminal:

```
source /usr/local/bin/virtualenvwrapper_lazy.sh
```

then try `lsvirtualenv` again.

If it works, you've got the stuff you need installed, but aren't
initializing it properly.

On Tue, Oct 6, 2015 at 9:13 PM, moxphere notifications@github.com wrote:

> Any command I type brings me the response:
> 
> -bash: lsvirtualenv: command not found
> 
> Should I consider install it again? Or create a different virtualenv?
> 
> Cassiano Gobbet
> cassiano.gobbet@gmail.com
> 
> On October 6, 2015 at 10:09:19 PM, Joanna S. Kao (notifications@github.com)
> wrote:
> 
> Typing in lsvirtualenv should list your current virtualenvs.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ajam/tarbell-big-read-template/issues/3#issuecomment-146048535
> .

## 

David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by cgobbet** [comment]
On 7 October 2015 at 00:52, David Eads notifications@github.com wrote:

> source /usr/local/bin/virtualenvwrapper_lazy.sh

​David, I tried and it worked. Listed the env and I managed to start it (it
seems).

Thanks a lot and my best wishes (Really!)​

**Comment by moxphere** [comment]
David, em again. I am trying to install Tarbell once more (now on a  company where I can use it) but still struggling. I am stuck trying to install virtualenvwrapper. I am trying to walk the path you taught before, but I'm stuck again.

I receive the message below: 

(terminal)

Mac-mini-de-Suporte:~ Cassiano$ pip install virtualenv virtualenvwrapper
Requirement already satisfied: virtualenv in /Library/Python/2.7/site-packages
Collecting virtualenvwrapper
  Using cached virtualenvwrapper-4.8.1-py2.py3-none-any.whl
Requirement already satisfied: virtualenv-clone in /Library/Python/2.7/site-packages (from virtualenvwrapper)
Collecting stevedore (from virtualenvwrapper)
  Using cached stevedore-1.26.0-py2.py3-none-any.whl
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /Library/Python/2.7/site-packages (from stevedore->virtualenvwrapper)
Collecting six>=1.9.0 (from stevedore->virtualenvwrapper)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, stevedore, virtualenvwrapper
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/27/z8r2xh990m5_h0vyz584sb340000gp/T/pip-2WOwlZ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Mac-mini-de-Suporte:~ Cassiano$ 

(/terminal)

Do you have any hints? (I still have a long time to go, I know...)
