### ISSUE TITLE
Modify template

### ISSUE THREAD

**Issue by fdaudens** [ajam/tarbell-big-read-template#4]
Hi,

Thank you for this amazing code, very well documented. I have a maybe stupid question, but I would like to fork it in order to add a content_type value named "quote" so that the row in value can automatically be treated as <blockquote>. And I'm wondering which file should I edit. I tried macro.html, without results. Could you help me?

(Here is the code I tried to add:

```
{% macro build_quote(quote_row) %}
<!-- {% macro build_quote(quote_row, quote_source_row) %} -->
<div class="row" {% if subhead_row.id %} id={{ subhead_row.id }} {% endif %}>
    <div class="col-sm-7 col-sm-offset-1 col-xs-10 col-xs-offset-1">
        <blockquote>{{ quote_row.value }}</blockquote>
<!--           <p class="quote_source">{{ quote_source_row.value }}</p>-->    
</div>
</div>
{% endmacro %}
```

**Comment by fdaudens** [comment]
(Here is the code I tried to add:

{% macro build_quote(quote_row) %}

<div class="row" {% if subhead_row.id %} id={{ subhead_row.id }} {% endif %}>
    <div class="col-sm-7 col-sm-offset-1 col-xs-10 col-xs-offset-1">
        <blockquote>{{ quote_row.value }}</blockquote>
    
</div>
</div>
{% endmacro %}

**Comment by joannaskao** [comment]
The `_macros.html` file is the correct file. 

What you have looks correct. Remember to add a new elif statement at the top of the file (like this: https://github.com/ajam/tarbell-big-read-template/blob/master/_macros.html#L11-L12).

Does that work now?

**Comment by fdaudens** [comment]
Arg, forgot to change one word. Works perfectly now. Thank you very much!
